export { HomePage } from './HomePage'
export { GettingStartedPage } from './GettingStartedPage'
export { NotFoundPage } from './NotFoundPage'
export { RedirectPage } from './RedirectPage'
export { ResumePage } from './ResumePage'
export { ProjectsPage } from './ProjectsPage'
export { ProjectDetailPage } from './ProjectDetailPage'
